### ISSUE TITLE
using GDCM handler to decode pixel data

### ISSUE THREAD

**Issue by NargesSayah** [conda-forge/gdcm-feedstock#26]
I'm trying to read and plot some DICOM files using Pydicom and GDCM handler, but I get an error although I have GDCM installed on my system (mac os x) through conda:
`$ conda install gdcm -c conda-forge`
And this is what I get:

> RuntimeError: The following handlers are available to decode the pixel data however they are missing required dependencies: GDCM (req. GDCM)

This error was raised when calling pixel_array() to decode the pixel data.
So, I specified the handler name by overwriting the dataset.py (passed handler_name='gdcm' as an input to convert_pixel_data) but still, I get:

> RuntimeError: The pixel data handler 'gdcm' is not available on your system. Please refer to the pydicom documentation for information on installing needed packages.

Attempting to import gdcm in my python interpreter throws an ImportError while opening the library (referenced from libgdcmCommon.2.8.dylib):

> Library not loaded: @rpath/libcrypto.1.1.dylib
>   Reason: image not found

Also, I can't use other handlers like pillow due to the Transfer Syntax UID of my data ('1.2.840.10008.1.2.4.70' (JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]))

**Comment by NargesSayah** [comment]
[This](https://pydicom.github.io/pydicom/stable/auto_examples/image_processing/reslice.html) is mainly the code, except for importing pylibjpeg and reading dicoms from file in my version. And here's the Traceback:

> Traceback (most recent call last):
>   File "/Users/narges/PycharmProjects/SBC/reslice_axial_sagittal_coronal.py", line 74, in <module>
>     img_shape = list(slices[0].pixel_array.shape)
>   File "/Users/narges/Library/Python/3.6/lib/python/site-packages/pydicom/dataset.py", line 1620, in pixel_array
>     self.convert_pixel_data()
>   File "/Users/narges/Library/Python/3.6/lib/python/site-packages/pydicom/dataset.py", line 1326, in convert_pixel_data
>     self._convert_pixel_data_without_handler()
>   File "/Users/narges/Library/Python/3.6/lib/python/site-packages/pydicom/dataset.py", line 1412, in _convert_pixel_data_without_handler
>     raise RuntimeError(msg + ', '.join(pkg_msg))
> RuntimeError: The following handlers are available to decode the pixel data however they are missing required dependencies: GDCM (req. GDCM)

**Comment by NargesSayah** [comment]
I just updated my python from Python 3.6.3 to Python 3.8 and now gdcm is working just fine!
